nomColsSitios = {'TRACKER':'TRACKER',
                 'AT&T ID':'S_ATT_ID',
                 'Nombre':'NOMBRE',
                 'ID LTE':'ID_LITE',
                 'ID Rojo':'ID_ROJO',
                 'ID Naranja':'ID_NARANJA',
                 'IDEN':'IDEN',
                 'Latitud':'LATITUD',
                 'Longitud':'LONGITUD',
                 'Estado':'ESTADO',
                 'Municipio':'MUNICIPIO',
                 'Mercado':'MERCADO',
                 'Region_Celular':'REGION_CELULAR',
                 'Region':'REGION',
                 'Vendor':'VENDOR',
                 'Cobertura':'COBERTURA',
                 'Tipo':'TIPO', 
                 'Proyecto':'PROYECTO',
                 'Clasificacion':'CLASIFICACION', 
                 'Tecnología':'TECNOLOGIA',
                 'Configuracion 3G':'CONFIGURACION_3G', 
                 'Configuracion 4G':'CONFIGURACION_4G',
                 'Configuracion 5G':'CONFIGURACION_5G', 
                 'IoT':'IOT',
                 'TDD':'TDD', 
                 'Trafico 3G/LTE/5G':'TRAFICO_3G_LTE_5G', 
                 'Trafico 3G':'TRAFICO_3G', 
                 'Trafico 4G':'TRAFICO_4G',
                 'Trafico 5G':'TRAFICO_5G',
                 'SL':'SL',
                 'Reubicación':'REUBICACION',
                 'NOTAS':'NOTAS',
                 'Comentario Operaciones':'COMENTARIO_OPERACIONES',
                 'Plan':'PLAN',
                 'B5_850':'ENE_3G_B5_850',
                 'B2_PCS':'ENE_3G_B2_PCS', 
                 'B4_AWS':'ENE_3G_B4_AWS',
                 'B26_800':'ENE_LTE_B26_800',
                 'B5_850.1':'ENE_LTE_B5_850',
                 'B2_PCS.1':'ENE_LTE_B2_PCS',
                 'B4_AWS.1':'ENE_LTE_B4_AWS',
                 'B7_2600':'ENE_LTE_B7_2600',
                 'B38_2600':'ENE_LTE_B38_2600',
                 'B7_2600.1':'ENE_5G_B7_2600',
                 'B38_2600.1':'ENE_5G_B38_2600',
                 'Comentario Operaciones.1':'ENE_COMENTARIO_OPERACIONES',
                 'Plan.1':'ENE_PLAN',
                 'B5_850.2':'FEB_3G_B5_850',
                 'B2_PCS.2':'FEB_3G_B2_PCS',
                 'B4_AWS.2':'FEB_3G_B4_AWS',
                 'B26_800.1':'FEB_LTE_B26_800',
                 'B5_850.3':'FEB_LTE_B5_850',
                 'B2_PCS.3':'FEB_LTE_B2_PCS',
                 'B4_AWS.3':'FEB_LTE_B4_AWS',
                 'B7_2600.2':'FEB_LTE_B7_2600',
                 'B38_2600.2':'FEB_LTE_B38_2600',
                 'B7_2600.3':'FEB_5G_B7_2600',
                 'B38_2600.3':'FEB_5G_B38_2600',
                 'Comentario Operaciones.2':'FEB_COMENTARIO_OPERACIONES',
                 'Plan.2':'FEB_PLAN',
                 'B5_850.4':'MAR_3G_B5_850',
                 'B2_PCS.4':'MAR_3G_B2_PCS',
                 'B4_AWS.4':'MAR_3G_B4_AWS',
                 'B26_800.2':'MAR_LTE_B26_800',
                 'B5_850.5':'MAR_LTE_B5_850',
                 'B2_PCS.5':'MAR_LTE_B2_PCS',
                 'B4_AWS.5':'MAR_LTE_B4_AWS',
                 'B7_2600.4':'MAR_LTE_B7_2600',
                 'B38_2600.4':'MAR_LTE_B38_2600',
                 'B7_2600.5':'MAR_5G_B7_2600',
                 'B38_2600.5':'MAR_5G_B38_2600',
                 'Comentario Operaciones.3':'MAR_COMENTARIO_OPERACIONES',
                 'Plan.3':'MAR_PLAN',
                 'B5_850.6':'ABR_3G_B5_850',
                 'B2_PCS.6':'ABR_3G_B2_PCS',
                 'B4_AWS.6':'ABR_3G_B4_AWS',
                 'B26_800.3':'ABR_LTE_B26_800',
                 'B5_850.7':'ABR_LTE_B5_850',
                 'B2_PCS.7':'ABR_LTE_B2_PCS',
                 'B4_AWS.7':'ABR_LTE_B4_AWS',
                 'B7_2600.6':'ABR_LTE_B7_2600',
                 'B38_2600.6':'ABR_LTE_B38_2600',
                 'B7_2600.7':'ABR_5G_B7_2600',
                 'B38_2600.7':'ABR_5G_B38_2600',
                 'Comentario Operaciones.4':'ABR_COMENTARIO_OPERACIONES',
                 'Plan.4':'ABR_PLAN',
                 'B5_850.8':'MAY_3G_B5_850',
                 'B2_PCS.8':'MAY_3G_B2_PCS',
                 'B4_AWS.8':'MAY_3G_B4_AWS',
                 'B26_800.4':'MAY_LTE_B26_800',
                 'B5_850.9':'MAY_LTE_B5_850',
                 'B2_PCS.9':'MAY_LTE_B2_PCS',
                 'B4_AWS.9':'MAY_LTE_B4_AWS',
                 'B7_2600.8':'MAY_LTE_B7_2600',
                 'B38_2600.8':'MAY_LTE_B38_2600',
                 'B7_2600.9':'MAY_5G_B7_2600',
                 'B38_2600.9':'MAY_5G_B38_2600',
                 'Comentario Operaciones.5':'MAY_COMENTARIO_OPERACIONES',
                 'Plan.5':'MAY_PLAN',
                 'B5_850.10':'JUN_3G_B5_850',
                 'B2_PCS.10':'JUN_3G_B2_PCS',
                 'B4_AWS.10':'JUN_3G_B4_AWS',
                 'B26_800.5':'JUN_LTE_B26_800',
                 'B5_850.11':'JUN_LTE_B5_850',
                 'B2_PCS.11':'JUN_LTE_B2_PCS',
                 'B4_AWS.11':'JUN_LTE_B4_AWS',
                 'B7_2600.10':'JUN_LTE_B7_2600',
                 'B38_2600.10':'JUN_LTE_B38_2600',
                 'B7_2600.11':'JUN_5G_B7_2600',
                 'B38_2600.11':'JUN_5G_B38_2600',
                 'Comentario Operaciones.6':'JUN_COMENTARIO_OPERACIONES',
                 'Plan.6':'JUN_PLAN',
                 'B5_850.12':'JUL_3G_B5_850',
                 'B2_PCS.12':'JUL_3G_B2_PCS',
                 'B4_AWS.12':'JUL_3G_B4_AWS',
                 'B26_800.6':'JUL_LTE_B26_800',
                 'B5_850.13':'JUL_LTE_B5_850',
                 'B2_PCS.13':'JUL_LTE_B2_PCS',
                 'B4_AWS.13':'JUL_LTE_B4_AWS',
                 'B7_2600.12':'JUL_LTE_B7_2600',
                 'B38_2600.12':'JUL_LTE_B38_2600',
                 'B7_2600.13':'JUL_5G_B7_2600',
                 'B38_2600.13':'JUL_5G_B38_2600',
                 'Comentario Operaciones.7':'JUL_COMENTARIO_OPERACIONES',
                 'Plan.7':'JUL_PLAN',
                 'B5_850.14':'AGO_3G_B5_850',
                 'B2_PCS.14':'AGO_3G_B2_PCS',
                 'B4_AWS.14':'AGO_3G_B4_AWS',
                 'B26_800.7':'AGO_LTE_B26_800',
                 'B5_850.15':'AGO_LTE_B5_850',
                 'B2_PCS.15':'AGO_LTE_B2_PCS',
                 'B4_AWS.15':'AGO_LTE_B4_AWS',
                 'B7_2600.14':'AGO_LTE_B7_2600',
                 'B38_2600.14':'AGO_LTE_B38_2600',
                 'B42_3500':'AGO_LTE_B42_3500',
                 'B7_2600.15':'AGO_5G_B7_2600',
                 'B38_2600.15':'AGO_5G_B38_2600',
                 'Comentario Operaciones.8':'AGO_COMENTARIO_OPERACIONES',
                 'Plan.8':'AGO_PLAN', 
                 'B5_850.16':'SEP_3G_B5_850',
                 'B2_PCS.16':'SEP_3G_B2_PCS',
                 'B4_AWS.16':'SEP_3G_B4_AWS',
                 'B26_800.8':'SEP_LTE_B26_800',
                 'B5_850.17':'SEP_LTE_B5_850',
                 'B2_PCS.17':'SEP_LTE_B2_PCS',
                 'B4_AWS.17':'SEP_LTE_B4_AWS',
                 'B7_2600.16':'SEP_LTE_B7_2600',
                 'B38_2600.16':'SEP_LTE_B38_2600',
                 'B42_3500.1':'SEP_LTE_B42_3500',
                 'B7_2600.17':'SEP_5G_B7_2600',
                 'B38_2600.17':'SEP_5G_B38_2600',
                 'Comentario Operaciones.9':'SEP_COMENTARIO_OPERACIONES',
                 'Plan.9':'SEP_PLAN',
                 'B5_850.18':'OCT_3G_B5_850',
                 'B2_PCS.18':'OCT_3G_B2_PCS',
                 'B4_AWS.18':'OCT_3G_B4_AWS',
                 'B26_800.9':'OCT_LTE_B26_800',
                 'B5_850.19':'OCT_LTE_B5_850',
                 'B2_PCS.19':'OCT_LTE_B2_PCS',
                 'B4_AWS.19':'OCT_LTE_B4_AWS',
                 'B7_2600.18':'OCT_LTE_B7_2600',
                 'B38_2600.18':'OCT_LTE_B38_2600',
                 'B42_3500.2':'OCT_LTE_B42_3500',
                 'B7_2600.19':'OCT_5G_B7_2600',
                 'B38_2600.19':'OCT_5G_B38_2600'}

nomColsFiltroSitios = {'TRACKER':'TRACKER', 
                       'AT&T ID':'ATT_ID_S', 
                       'Nombre':'NOMBRE',
                       'Latitud':'LATITUD', 
                       'Longitud':'LONGITUD', 
                       'Estado':'ESTADO',
                       'Municipio':'MUNICIPIO', 
                       'Mercado':'MERCADO', 
                       'Region_Celular':'REGION_CELULAR', 
                       'Region':'REGION',
                       'Vendor':'VENDOR', 
                       'Clasificacion':'CLASIFICACION', 
                       'Tecnología':'TECNOLOGIA'}

nomColsFO = {'ID_ATT':'ID_ATT_F',
             'TX':'TX', 
             'TX Grupos':'TX_GRUPOS',
             'TX Detalle':'TX_DETALLE',
             'Control':'CONTROL', 
             'Fecha':'FECHA', 
             'POC':'POC', 
             'Observaciones':'OBSERVACIONES',
             'ID':'TRACKER',
             'ID AT&T':'ATT_ID',
             'NOMBRE':'NOMBRE', 
             'LATITUD':'LATITUD',	
             'LONGITUD':'LONGITUD',
             'Estado':'ESTADO', 
             'Municipio':'MUNICIPIO',
             'Mercado':'MERCADO',
             'Mercado FO':'MERCADO_FO', 
             'Region_Celular':'REGION_CELULAR',
             'AGREGADOR':'AGREGADOR',
             'AÑO':'AÑO',
             'PROYECTO':'PROYECTO',
             'TOPOLOGÍA':'TOPOLOGIA', 
             'SEGMENTO IPBH':'SEGMENTO_IPBH', 
             'STATUS':'STATUS', 
             'TX.1':'TX_FO'}

nomColsFiltroFO = {'ID_ATT':'ID_ATT_F',
                   'TX':'TX',
                   'TX Grupos':'TX_GRUPOS', 
                   'TX Detalle':'TX_DETALLE',
                   'Control':'CONTROL', 
                   'Fecha':'FECHA', 
                   'POC':'POC', 
                   'Observaciones':'OBSERVACIONES',
                   'Mercado FO':'MERCADO',
                   'AÑO':'AÑO', 
                   'PROYECTO':'PROYECTO', 
                   'TOPOLOGÍA':'TOPOLOGIA',
                   'SEGMENTO IPBH':'SEGMENTO_IPBH', 
                   'STATUS':'STATUS' }

nomColsAgg = {'ID_ATT':'ID_ATT_A',
              'TX':'TX_A',
              'TX Grupos AGG':'TX_GRUPOS_A',
              'TX Detalle AGG':'TX_DETALLE_A',
              'Control':'CONTROL',	
              'Fecha':'FECHA',
              'POC':'POC',
              'Observaciones':'OBSERVACIONES',
              'ID':'TRACKER',
              'ID AT&T':'ATT_ID',
              'NOMBRE':'NOMBRE',	
              'LATITUD':'LATITUD',
              'LONGITUD':'LONGITUD',
              'Estado':'ESTADO',
              'Municipio':'MUNICIPIO',
              'Mercado':'MERCADO',
              'Mercado FO':'MERCADO_FO',
              'Region_Celular':'REGION_CELULAR',
              'AGREGADOR':'AGREGADOR',
              'AÑO':'AÑO',
              'PROYECTO':'PROYECTO',
              'TOPOLOGÍA':'TOPOLOGIA',
              'SEGMENTO IPBH':'SEGMENTO_IPBH', 
              'STATUS':'STATUS',
              'TX.1':'TX_FO'}

nomColsFiltroAgg = {'ID_ATT':'ATT_ID_A',
                    'TX':'TX',
                    'TX Grupos AGG':'TX_GRUPOS_AGG',
                    'TX Detalle AGG':'TX_DETALLE_AGG',
                    'Control':'CONTROL',
                    'Fecha':'FECHA',
                    'POC':'POC',
                    'Observaciones':'OBSERVACIONES',
                    'Mercado FO':'MERCADO_FO',
                    'AGREGADOR':'AGREGADOR',
                    'AÑO':'AÑO',
                    'PROYECTO':'PROYECTO',
                    'TOPOLOGÍA':'TOPOLOGIA',
                    'SEGMENTO IPBH':'SEGMENTO_IPBH',
                    'STATUS':'STATUS'}


nomColsProyeccion = { 'ID_ATT':'ID_ATT_P',
                      'TX':'TX',
                      'TX Grupos Proyeccion':'TX_GRUPOS_PROYECCION',
                      'TX Detalle Proyecccion':'TX_DETALLE_PROYECCION',	
                      'Control':'CONTROL',
                      'AÑO PROYECCION':'AÑO_PROYECCION',
                      'Fecha':'FECHA',
                      'POC':'POC',
                      'Observaciones':'OBSERVACIONES',
                      'ID':'TRACKER',
                      'ID AT&T':'ATT_ID',
                      'NOMBRE':'NOMBRE',
                      'LATITUD':'LATITUD',
                      'LONGITUD':'LONGITUD',
                      'Estado':'ESTADO',
                      'Municipio':'MUNICIPIO',
                      'Mercado':'MERCADO',
                      'Mercado FO':'MERCADO_FO',
                      'Region_Celular':'REGION_CELULAR',
                      'AGREGADOR':'AGREGADOR',
                      'AÑO':'AÑO',
                      'PROYECTO':'PROYECTO',
                      'TOPOLOGÍA':'TOPOLOGIA',
                      'SEGMENTO IPBH':'SEGMENTO_IPBH',
                      'STATUS':'STATUS',
                      'TX.1':'TX_F'}

nomColsFiltroProyeccion = {'ID_ATT':'ID_ATT_P',
                           'TX':'TX',
                           'TX Grupos Proyeccion':'TX_GRUPOS_PROYECCION',
                           'TX Detalle Proyecccion':'TX_DETALLE_PROYECCION',	
                           'Control':'CONTROL',
                           'AÑO PROYECCION':'AÑO_PROYECCION',
                           'Fecha':'FECHA',
                           'POC':'POC',
                           'Observaciones':'OBSERVACIONES', 	
                           'Mercado FO':'MERCADO_FO',
                           'AÑO':'AÑO',
                           'PROYECTO':'PROYECTO',
                           'TOPOLOGIA':'TOPOLOGIA',
                           'STATUS':'STATUS' }


nomColsMigracion = {'ID ATT':'ID_ATT_M',
                    'Origen TX':'ORIGEN_TX',
                    'TX Grupos':'TX_GRUPOS',
                    'TX Detalle':'TX_DETALLE',
                    'Control':'CONTROL',	
                    'Fecha':'FECHA',
                    'POC':'POC',
                    'Observaciones':'OBSERVACIONES',
                    'ID Panda':'ID_PANDA',
                    'ID_ATT':'ID_ATT',	
                    'Site Name':'SITE_NAME',
                    'MARKET':'MARKET',
                    'Proyecto':'PROYECTO',
                    'Real Migracion':'REAL_MIGRACION',
                    'Scope':'SCOPE',	
                    'Panda':'PANDA', 
                    'Status':'STATUS',
                    'TX TYPE':'TX_TYPE',
                    'AT&T ID':'ATT_ID',
                    'Latitud':'LATITUD',	
                    'Longitud':'LONGITUD',
                    'Estado':'ESTADO',
                    'Municipio':'MUNICIPIO',
                    'Mercado':'MERCADO',
                    'Region_Celular':'REGION_CELULAR',	
                    'Clasificacion':'CLASIFICACION',
                    'Control de cambios RAN':'CONTROL_DE_CAMBIOS_RAN'}

nomColsMW = {'ATTID ':'ATT_ID_MW',
            'TX MW':'TX_MW',
            'TX Grupos MW':'TX_GRUPOS_MW',
            'TX Detalle MW':'TX_DETALLE_MW',
            'Control':'CONTROL', 
            'Fecha':'FECHA',
            'POC':'POC',
            'Observaciones':'OBSERVACIONES',
            'Nombre':'NOMBRE',
            'Latitud':'LATITUD',
            'Longitud':'LONGITUD',
            'Estado':'ESTADO',
            'Municipio':'MUNICIPIO',
            'Mercado':'MERCADO',
            'Region_Celular':'REGION_CELULAR',
            'Control de cambios RAN':'CONTROL_DE_CAMBIOS_RAN',
            'Proyecto Migrados':'PROYECTO_MIGRADOS',
            'Real Migracion':'REAL_MIGRACION',
            'TX Origen':'TX_ORIGEN',
            'Medio TX \nGrupos':'MEDIO_TX_GRUPOS',
            'TX Detalle':'TX_DETALLE',
            'Panda':'PANDA',
            'Status':'STATUS',	
            'TX TYPE':'TX_TYPE',
            'Capacidad 1G':'CAPACIDAD_1G',
            'Sitio A':'SITIO_A',
            'Sitio B':'SITIO_B',
            'Enlace':'ENLACE',
            'Tecnologia':'TECNOLOGIA',
            'Agregador Grupo':'AGREGADOR_GRUPO',
            'Agregador Detalle':'AGREGADOR_DETALLE',
            'Agregador':'AGREGADOR_1',
            'Tracker':'TRACKER',
            'ATTID':'ATT_ID', 
            'Sitio A':'SITE_A',
            'Sitio B.1':'SITE_B',
            'Link':'LINK',
            'Agregador.1':'AGREGADOR_2',
            'Site 1':'SITE_1',
            'Site 2':'SITE_2',
            'Site 3':'SITE_3',
            'Site 4':'SITE_4',
            'Site 5':'SITE_5',
            'Site 6':'SITE_6',
            'Site 7':'SITE_7',
            'Site 8':'SITE_8',
            'Site 9':'SITE_9',
            'Site 10':'SITE_10',
            'Sitios Carga':'SITIOS_CARGA',
            'Tipo':'TIPO',
            'ATTID.1':'ATTID',
            'TECNOLOGIA ACTUAL':'TECNOLOGIA_ACTUAL',
            'Capacidad (Mbps)':'CAPACIDAD_MBPS',
            'Utilización (Mbps)':'UTILIZACIÓN_MBPS',
            'Flag H':'FLAG_H',
            'Numero_de_Certificado':'NUMERO_DE_CERTIFICADO',
            'Numero_de_Link':'NUMERO_DE_LINK',
            'Identificador_Certificado':'IDENTIFICADOR_CERTIFICADO',
            'Concesionario':'CONCESIONARIO',
            'Responsable_Cons':'RESPONSABLE_CONS',
            'Dirección_Cons':'DIRECCION_CONS',
            'Teléfono_Cons':'TELEFONO_CONS',	
            'E-mail_Cons':'E_MAIL_CONS',
            'Usuaruo_Final':'USUARIO_FINAL',
            'Responsable_Us':'RESPONSABLE_US',
            'Dirección_Us':'DIRECCION_US',	
            'Teléfono_Us':'TELEFONO_US',
            'E-mail_Us':'E_MAIL_US',
            'Fecha_solicitud':'FECHA_SOLICITUD',
            'Fecha _Constancia':'FECHA_CONSTANCIA',	
            'Fecha de cancelación':'FECHA_DE_CANCELACION',
            'Motivo':'MOTIVO',
            'Nombre_A':'NOMBRE_A',
            'Domicilio_A':'DOMICILIO_A',	
            'Ciudad_A':'CIUDAD_A',
            'Clave Estado A':'CLAVE_ESTADO_A',
            'Latitud_grad_A':'LATITUD_GRAD_A',
            'Latitud_min_A':'LATITUD_MIN_A',	
            'Latitud_seg_A':'LATITUD_SEG_A',
            'Longitud_grad_A':'LONGITUD_GRAD_A',
            'Longitud_min_A':'LONGITUD_MIN_A',
            'Longitud_seg_A':'LONGITUD_SEG_A',
            'ASNM_A':'ASNM_A',
            'Azimut_A':'AZIMUT_A',
            'Nombre_B':'NOMBRE_B',
            'Domicilio_B':'DOMICILIO_B',	
            'Ciudad_B':'CIUDAD_B',
            'Clave Estado B':'CLAVE_ESTADO_B',
            'Latitud_grad_B':'LATITUD_GRAD_B',
            'Latitud_min_B':'LATITUD_MIN_B',	
            'Latitud_seg_B':'LATITUD_SEG_B',
            'Longitud_grad_B':'LONGITUD_GRAD_B',
            'Longitud_min_B':'LONGITUD_MIN_B',
            'Longitud_seg_B':'LONGITUD_SEG_B',
            'ASNM_B':'ASNM_B',
            'Azimut_B':'AZIMUT_B',
            'Longitud_Enlace':'LONGITUD_ENLACE',
            'Banda_Frecuencia':'BANDA_FRECUENCIA',
            'Frecuencia_Tx':'FRECUENCIA_TX',
            'Frecuencia_Rx':'FRECUENCIA_RX',	
            'Marca_Radio':'MARCA_RADIO',
            'Modelo_Radio':'MODELO_RADIO',
            'Modulación':'MODULACION',
            'Emisión':'EMISION',	
            'Ancho_Banda':'ANCHO_BANDA',
            'TX_Planned':'TX_PLANNED',
            'Separación_canal':'SEPARACION_CANAL',	
            'Sub_Banda_Op':'SUB_BANDA_OP',
            'Separación_Duplex':'SEPARACION_DUPLEX',
            'Umbra_Recepción':'UMBRA_RECEPCION',	
            'Tasa de Bits Umbral':'TASA_DE_BITS_UMBRAL',
            'PIRE':'PIRE',
            'PIRE_A':'PIRE_A',
            'PIRE_B':'PIRE_B',
            'Velocidad_Tx':'VELOCIDAD_TX',
            'Capacidad_Canales':'CAPACIDAD_CANALES',
            'Homologación_Equipo':'HOMOLOGACION_EQUIPO',	
            'Configuración_Enlace':'CONFIGURACION_ENLACE',
            'Antena_Tipo_A':'ANTENA_TIPO_A',
            'Antena_Marca_A':'ANTENA_MARCA_A',
            'Antena_Modelo_A':'ANTENA_MODELO_A',
            'Antena_Diámetro_A':'ANTENA_DIAMETRO_A',
            'Antena_Ganancia_A':'ANTENA_GANANCIA_A',	
            'Antena_Polarización_A':'ANTENA_POLARIZACION_A',
            'Antena_Angulo_abertura_A':'ANTENA_ANGULO_ABERTURA_A',	
            'Antena_Angulo_elevación_A':'ANTENA_ANGULO_ELEVACION_A',
            'Modelo_Radio_B':'MODELO_RADIO_B',
            'Antena_Tipo_B':'ANTENA_TIPO_B',	
            'Antena_Marca_B':'ANTENA_MARCA_B',
            'Antena_Modelo_B':'ANTENA_MODELO_B',
            'Antena_Diámetro_B':'ANTENA_DIAMETRO_B',
            'Antena_Ganancia_B':'ANTENA_GANANCIA_B',
            'Antena_Polarización_B':'ANTENA_POLARIZACION_B',	
            'Antena_Angulo_abertura_B':'ANTENA_ANGULO_ABERTURA_B',
            'Antena_Angulo_elevación_B':'ANTENA_ANGULO_ELEVACION_B',	
            'Línea_Marca_A':'LINEA_MARCA_A',
            'Línea_tipo_A':'LINEA_TIPO_A',
            'Línea_Longitud_A':'LINEA_LONGITUD_A',
            'Línea_atenuación_A':'LINEA_ATENUACION_A',
            'Otras Pérdidas Tx A':'OTRAS_PERDIDAS_TX_A',
            'Otras Pérdidas Rx A':'OTRAS_PERDIDAS_RX_A',
            'Línea_Marca_B':'LINEA_MARCA_B','Línea_tipo_B':'LINEA_TIPO_B',	
            'Línea_Longitud_B':'LINEA_LONGITUD_B',
            'Línea_atenuación_B':'LINEA_ATENUACION_B',
            'Otras Pérdidas Tx B':'OTRAS_PERDIDAS_TX_B',	
            'Otras Pérdidas Rx B':'OTRAS_PERDIDAS_RX_B',
            'Edificio_Altura_A':'EDIFICIO_ALTURA_A',
            'Torre_Altura_A':'TORRE_ALTURA_A',
            'Torre_Antena_Altura_A':'TORRE_ANTENA_ALTURA_A',
            'Torre_Tipo_A':'TORRE_TIPO_A',
            'Edificio_Altura _B':'EDIFICIO_ALTURA_B',
            'Torre_Altura_B':'TORRE_ALTURA_B',
            'Torre_Antena_Altura_B':'TORRE_ANTENA_ALTURA_B',	
            'Torre_Tipo_B':'TORRE_TIPO_B',
            'Pot Tx A':'POT_TX_A',
            'Rx_Planned_A':'RX_PLANNED_A',
            'Pote Tx B':'POTE_TX_B',
            'Rx_Planned_B':'RX_PLANNED_B',	
            'No_Channel':'NO_CHANNEL',
            'Channel ID  A':'CHANNEL_ID_A',
            'Channel ID  B':'CHANNEL_ID_B',
            'Observaciones Configuracion':'OBSERVACIONES_CONFIGURACION', 
            'Proyecto':'PROYECTO',
            'Solicitud':'SOLICITUD',
            'Ellipse':'ELLIPSE',
            'Google':'GOOGLE',
            'Orden de Trabajp':'ORDEN_DE_TRABAJO',	
            'Contratista':'CONTRATISTA',
            'Protocolo de Recepcion':'PROTOCOLO_DE_RECEPCION',
            'Rx med A':'RX_MED_A',
            'Rx Med B':'RX_MED_B',
            'Gestion':'GESTION',
            'IPLocal':'IPLOCAL',
            'IP Remoto':'IP_REMOTO',
            'No Serie IDU Local':'NO_SERIE_IDU_LOCAL',
            'No Serie ODU Local':'NO_SERIE_ODU_LOCAL',
            'No Serie IDU Remoto':'NO_SERIE_IDU_REMOTO',
            'No Serie ODU Remoto':'NO_SERIE_ODU_REMOTO',
            'Observaciones Ingenieria':'OBSERVACIONES_INGENIERIA',
            'Desmontajes':'DESMONTAJES',
            'Fecha.1':'FECHA_2',
            'Responsabe':'RESPONSABLE',			
        }

nomColsCarrier={'ID_ATT':'ID_ATT_C',	
                'TX':'TX',	
                'TX Grupos':'TX_GRUPOS',	
                'TX Detalle':'TX_DETALLE',	
                'Control':'CONTROL',	
                'Fecha de Alta o Baja':'FECHA_ALTA_BAJA',	
                'POC':'POC',	
                'Observaciones':'OBSERVACIONES',	
                'TX Carrier':'TX_CARRIER',	
                'Proyecto F.O  ':'PROYECTO_FO',  	
                'Segundo Puerto Habilitado':'SEGUNDO_PUERTO_HABILITADO',	
                'CID Carrier':'CID_CARRIER',	
                'Región':'REGION',	
                'Mercado':'MERCADO',	
                'Punta A Naming Convention':'PUNTA_A_NAMING_CONVECTION',	
                'Punta A ID Sitio':'PUNTA_A_ID_SITIO',	
                'Punta A Nombre Sitio':'PUNTA_A_NOMBRE_SITIO',	
                'Lat. Punta A':'LATITUD_PUNTA_A',	
                'Long. Punta A':'LONGITUD_PUNTA_A',	
                'Punta B Naming Convention':'PUNTA_B_NAMING_CONVECTION',	
                'Punta B ID Sitio':'PUNTA_B_ID_SITIO',	
                'Punta B Nombre Sitio':'PUNTA_B_NOMBRE_SITIO',	
                'Lat. Punta B':'LATITUD_PUNTA_B',	
                'Long. Punta B':'LONGITUD_PUNTA_B',	
                'Carrier':'CARRIER', 	
                'Tipo Enlace':'TIPO_ENLACE',	
                'Proyecto Principal':'PROYECTO_PRINCIPAL',	
                'Fase ':'FASE', 	
                'Capacidad (Mbps)':'CAPACIDAD_MBPS',	
                'Estatus':'ESTATUS',	
                'TRACKER':'TRACKER',	
                'AT&T ID 2':'ATT_ID',	
                'Nombre':'NOMBRE',	
                'Control de cambios RAN':'CONTROL_DE_CAMBIOS_RAN',	
                'Base Origen \nTX':'BASE_ORIGEN_TX',	
                'Grupos \nMedio TX ':'GRUPOS_MEDIO_TX',	
                'TX Detalle2':'TX_DETALLE_2',	
                'Base Origen Proyeccion':'BASE_ORIGEN_PROYECCION' }


nomColsPon = {
                'ID_ATT':'ID_ATT_PON',	
                'TX':'TX_PON',	
                'TX Grupos':'TX_GRUPOS_PON',	
                'TX Detalle':'TX_DETALLE_PON',	
                'Control':'CONTROL_PON',	
                'Fecha':'FECHA_PON',	
                'POC':'POC_PON',	
                'Observaciones':'OBSERVACIONES_PON',	
                'Region':'REGION',	
                'Ciudad':'CIUDAD',	
                'OLT Name':'OLT_NAME_1',	
                'OLT ATT ID':'OLT_ATT_ID',	
                'OLT IP':'OLT_IP',	
                'OLT NAME':'OLT_NAME_2',	
                'OLT Type':'OLT_TYPE',	
                'Frame ID':'FRAME_ID',	
                'Slot ID':'SLOT_ID',	
                'Port ID':'PORT_ID',	
                'ONU ID':'ONU_ID',	
                'ONT Name':'ONT_NAME',	
                'ONT OLD NAME':'ONT_OLD_NAME',	
                'SITE ID ':'SITE_ID', 	
                'ID AT&T':'ID_ATT',	
                'Con Servivios / Sin Servicios':'CON_SIN_SERVICIOS',	
                'ONU IP':'ONU_IP',	
                'ONT Type':'ONT_TYPE',	
                'ONU TYPE':'ONU_TYPE',	
                'SN/MAC':'SN_MAC',	
                'Vendor ':'VENDOR', 	
                'Running Status':'RUNNIG_STATUS',	
                'Operation Status':'OPERATION_STATUS' }

nomColsPanda={  'TRACKER':'TRACKER',  	
                'NAMING CONVENTION':'NAMING_CONVENTION',  	
                'SITE NAME':'SITE_NAME',  	
                'PLACEMENT':'PLACEMENT',  	
                'PROJECT':'PROJECT',  
                'ID LOCATION':'ID_LOCATION',	 
                'ID SITE':'ID_SITE',	 
                'PANDA CODE':'PANDA_CODE',  
                'SITE TYPE':'SITE_TYPE',  
                'STATUS':'STATUS',  
                'MILESTONE':'MILESTONE',  
                'BATCH':'BATCH',  
                'MARKET':'MARKET',  
                'CLUSTER':'CLUSTER',	 
                'EQUIPMENT':'EQUIPMENT',  
                'YEAR PLAN':'YEAR_PLAN',  
                'ISSUE TYPE':'ISSUE_TYPE',  
                'OWNER':'OWNER',  
                'OWNER ID':'OWNER_ID',  
                'CANDIDATE':'CANDIDATE',  
                'INSTALL TYPE':'INSTALL_TYPE',  
                'TOWER TYPE':'TOWER_TYPE',  
                'BUILDING HT':'BUILDING_HT',	 
                'TOWER HT':'TOWER_HT',  
                'TX TYPE':'TX_TYPE',	 
                'LATITUDE':'LATITUDE',  
                'LONGITUDE':'LONGITUDE',  
                'MUNICIPALITY':'MUNICIPALITY',  
                'STATE':'STATE',  
                'CONTAINER TYPE':'CONTAINER_TYPE',  
                'SOLUTION TYPE':'SOLUTION_TYPE',  
                'PROJECT RELEASED':'PROJECT_RELEASED_1',  											
                'Unnamed: 32':'PROJECT_RELEASED_2', 											
                'Unnamed: 33':'PROJECT_RELEASED_3',  											
                'Unnamed: 34':'PROJECT_RELEASED_4',  											
                'Unnamed: 35':'PROJECT_RELEASED_5',  											
                'Unnamed: 36':'PROJECT_RELEASED_6', 											
                'Unnamed: 37':'PROJECT_RELEASED_7', 											
                'Unnamed: 38':'PROJECT_RELEASED_8', 											
                'Unnamed: 39':'PROJECT_RELEASED_9', 											
                'Unnamed: 40':'PROJECT_RELEASED_10', 											
                'Unnamed: 41':'PROJECT_RELEASED_11', 											
                'Unnamed: 42':'PROJECT_RELEASED_12', 											
                'Unnamed: 43':'PROJECT_RELEASED_13', 											
                'Unnamed: 44':'PROJECT_RELEASED_14', 											
                'Unnamed: 45':'PROJECT_RELEASED_15', 											
                'Unnamed: 46':'PROJECT_RELEASED_16', 
                'Unnamed: 47':'PROJECT_RELEASED_17' }

nomColsTellus ={
                   'SYSTEM ID':'SYSTEM_ID',	
                    'SITE':'SITE',	
                    'NAME':'NAME',	
                    'GSM':'GSM',	
                    'UMTS':'UMTS',	
                    'LTE':'LTE',	
                    'HIERARCHY':'HIERARCHY',	
                    'COLLOS':'COLLOS',	
                    'CVE INSTALL TYPE':'CVE_INSTALL_TYPE',	
                    'OPERATIVE STATUS':'OPERATIVE_STATUS',	
                    'DATE ONAIR':'DATE_ONAIR',	
                    'OWNER':'OWNER',	
                    'ADDRESS':'ADDRESS',	
                    'MUNICIPALITY':'MUNICIPALITY',	
                    'STATE NAME':'STATE_NAME',	
                    'MARKET':'MARKET',	
                    'LATITUDE':'LATITUDE',	
                    'LONGITUDE':'LONGITUDE',	
                    'CELL REGION':'CELL_REGION',	
                    'CELLOWNER':'CELLOWNER',	
                    'CELLOWNER TELEPHONE':'CELLOWNER_TELEPHONE',	
                    'CELLOWNER EMAIL':'CELLOWNER_EMAIL',	
                    'COORDINATOR':'COORDINATOR',	
                    'COORDINATOR TELEPHONE':'COORDINATOR_TELEPHONE',	
                    'COORDINATOR EMAIL':'COORDINATOR_EMAIL',	
                    'MANAGER':'MANAGER',	
                    'MANAGER TELEPHONE':'MANAGER_TELEPHONE',	
                    'MANAGER EMAIL':'MANAGER_EMAIL',	
                    'DIRECTOR':'DIRECTOR',	
                    'DIRECTOR TELEPHONE':'DIRECTOR_TELEPHONE',	
                    'DIRECTOR EMAIL':'DIRECTOR_EMAIL',	
                    'COORDINATION':'COORDINATION',	
                    'MANAGEMENT':'MANAGEMENT',	
                    'REGION':'REGION'}


nomColsCapacidadManual ={
                        'ID_ATT':'ID_ATT',	
                        'TX':'TX',	
                        'TX Grupos Manual':'TX_GRUPOS_MANUAL',	
                        'TX Detalle Manual':'TX_DETALLE_MANUAL',	
                        'Control':'CONTROL',	
                        'Fecha':'FECHA',	
                        'POC':'POC',	
                        'Observaciones':'OBSERVACIONES',	
                        'TRACKER':'TRACKER',	
                        'AT&T ID':'ATT_ID',	
                        'Nombre':'NOMBRE',	
                        'Latitud':'LATITUD',	
                        'Longitud':'LONGITUD',	
                        'Estado':'ESTADO',	
                        'Municipio':'MUNICIPIO',	
                        'Mercado':'MERCADO',	
                        'Region_Celular':'REGION_CELULAR',	
                        'Region':'REGION',	
                        'Vendor':'VENDOR',	
                        'Cobertura':'COBERTURA',	
                        'Tipo':'TIPO',	
                        'Proyecto':'PROYECTO',	
                        'Clasificacion':'CLASIFICACION',	
                        'Control de cambios RAN':'CONTROL_CAMBIOS_RAN',	
                        'Base Origen TX':'BASE_ORIGEN_TX',	
                        "Grupos \nMedio TX ":'GRUPOS_MEDIO_TX',	
                        'TX Detalle':'TX_DETALLE',	
                        'Capacidad':'CAPACIDAD',	
                        'Control':'CONTROL'}