from django.db import models

class SitiosTotales(models.Model):
    TRACKER = models.CharField(max_length = 50, blank=False, null = False)	
    S_ATT_ID= models.CharField(primary_key=True,max_length = 50, blank=False, null = False)	
    NOMBRE	= models.CharField(max_length = 50, blank=False, null = False)
    ID_LITE	= models.CharField(max_length = 50, blank=False, null = False)
    ID_ROJO	= models.CharField(max_length = 50, blank=False, null = False)
    ID_NARANJA = models.CharField(max_length = 50, blank=False, null = False)
    IDEN = models.CharField(max_length = 50, blank=False, null = False)
    LATITUD	= models.CharField(max_length = 50, blank=False, null = False)
    LONGITUD = models.CharField(max_length = 50, blank=False, null = False)
    ESTADO = models.CharField(max_length = 50, blank=False, null = False)
    MUNICIPIO = models.CharField(max_length = 50, blank=False, null = False)
    MERCADO	= models.CharField(max_length = 50, blank=False, null = False)
    REGION_CELULAR = models.CharField(max_length = 50, blank=False, null = False)
    REGION = models.CharField(max_length = 50, blank=False, null = False)
    VENDOR = models.CharField(max_length = 50, blank=False, null = False)
    COBERTURA = models.CharField(max_length = 50, blank=False, null = False)
    TIPO = models.CharField(max_length = 50, blank=False, null = False)
    PROYECTO = models.CharField(max_length = 50, blank=False, null = False)
    CLASIFICACION = models.CharField(max_length = 50, blank=False, null = False)
    TECNOLOGIA = models.CharField(max_length = 50, blank=False, null = False)
    CONFIGURACION_3G = models.CharField(max_length = 50, blank=False, null = False)
    CONFIGURACION_4G = models.CharField(max_length = 50, blank=False, null = False)
    CONFIGURACION_5G = models.CharField(max_length = 50, blank=False, null = False)
    IOT = models.CharField(max_length = 50, blank=False, null = False)
    TDD	= models.CharField(max_length = 50, blank=False, null = False)
    TRAFICO_3G_LTE_5G = models.CharField(max_length = 50, blank=False, null = False)
    TRAFICO_3G = models.CharField(max_length = 50, blank=False, null = False)
    TRAFICO_4G = models.CharField(max_length = 50, blank=False, null = False)
    TRAFICO_5G = models.CharField(max_length = 50, blank=False, null = False)
    SL = models.CharField(max_length = 50, blank=False, null = False)
    REUBICACION	= models.CharField(max_length = 50, blank=False, null = False)
    COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    PLAN = models.CharField(max_length = 50, blank=False, null = False)
    ENE_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    ENE_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    ENE_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    ENE_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    ENE_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    ENE_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    ENE_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    ENE_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    ENE_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    ENE_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    ENE_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    ENE_COMENTARIO_OPERACIONES= models.CharField(max_length = 50, blank=False, null = False)
    ENE_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    FEB_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    FEB_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    FEB_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    FEB_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    FEB_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    FEB_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    FEB_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    FEB_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    FEB_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    FEB_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    FEB_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    FEB_COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    FEB_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    MAR_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    MAR_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    MAR_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    MAR_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    MAR_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    MAR_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    MAR_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    MAR_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    MAR_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    MAR_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    MAR_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    MAR_COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    MAR_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    ABR_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    ABR_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    ABR_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    ABR_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    ABR_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    ABR_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    ABR_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    ABR_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    ABR_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    ABR_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    ABR_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    ABR_COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    ABR_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    MAY_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    MAY_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    MAY_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    MAY_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    MAY_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    MAY_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    MAY_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    MAY_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    MAY_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    MAY_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    MAY_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    MAY_COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    MAY_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    JUN_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    JUN_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    JUN_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    JUN_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    JUN_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    JUN_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    JUN_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    JUN_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    JUN_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    JUN_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    JUN_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    JUN_COMENTARIO_OPERACIONES	= models.CharField(max_length = 50, blank=False, null = False)
    JUN_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    JUL_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    JUL_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    JUL_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    JUL_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    JUL_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    JUL_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    JUL_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    JUL_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    JUL_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    JUL_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    JUL_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    JUL_COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    JUL_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    AGO_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    AGO_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    AGO_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    AGO_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    AGO_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    AGO_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    AGO_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    AGO_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    AGO_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    AGO_LTE_B42_3500 = models.CharField(max_length = 50, blank=False, null = False)
    AGO_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    AGO_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    AGO_COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    AGO_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    SEP_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    SEP_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    SEP_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    SEP_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    SEP_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    SEP_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    SEP_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    SEP_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    SEP_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    SEP_LTE_B42_3500 = models.CharField(max_length = 50, blank=False, null = False)
    SEP_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    SEP_5G_B38_2600	= models.CharField(max_length = 50, blank=False, null = False)
    SEP_COMENTARIO_OPERACIONES = models.CharField(max_length = 50, blank=False, null = False)
    SEP_PLAN = models.CharField(max_length = 50, blank=False, null = False)
    OCT_3G_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    OCT_3G_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    OCT_3G_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    OCT_LTE_B26_800	= models.CharField(max_length = 50, blank=False, null = False)
    OCT_LTE_B5_850 = models.CharField(max_length = 50, blank=False, null = False)
    OCT_LTE_B2_PCS = models.CharField(max_length = 50, blank=False, null = False)
    OCT_LTE_B4_AWS = models.CharField(max_length = 50, blank=False, null = False)
    OCT_LTE_B7_2600	= models.CharField(max_length = 50, blank=False, null = False)
    OCT_LTE_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    OCT_LTE_B42_3500 = models.CharField(max_length = 50, blank=False, null = False)
    OCT_5G_B7_2600 = models.CharField(max_length = 50, blank=False, null = False)
    OCT_5G_B38_2600 = models.CharField(max_length = 50, blank=False, null = False)
    class Meta: 
        verbose_name = 'Sitio'
        verbose_name_plural = 'Sitios'
        db_table = "sitiosTotales"

# class Filtro_SitiosTotales(models.Model):
#     TRACKER	= models.CharField()
#     ATT_ID_S = models.CharField()
#     NOMBRE = models.CharField()
#     LATITUD = models.CharField()	
#     LONGITUD= models.CharField()	
#     ESTADO = models.CharField()
#     MUNICIPIO = models.CharField()	
#     MERCADO	= models.CharField()
#     REGION_CELULAR = models.CharField()
#     REGION = models.CharField()
#     VENDOR = models.CharField()
#     CLASIFICACION = models.CharField()
#     TECNOLOGIA = models.CharField()
  
#     class Meta:
#         db_table = "tb1_sitiosTotales"

 
class FibraOptica(models.Model):
    ID_ATT_F = models.CharField(max_length = 50, blank=False, null = False)	
    TX = models.CharField(max_length = 50, blank=False, null = False)	
    TX_GRUPOS = models.CharField(max_length = 50, blank=False, null = False)	
    TX_DETALLE = models.CharField(max_length = 50, blank=False, null = False)	
    CONTROL = models.CharField(max_length = 50, blank=False, null = False)	
    FECHA = models.DateField(max_length = 50, blank=False, null = False)	
    POC	= models.CharField(max_length = 50, blank=False, null = False)	
    OBSERVACIONES = models.CharField(max_length = 50, blank=False, null = False)	
    TRACKER = models.CharField(max_length = 50, blank=False, null = False)	
    ATT_ID = models.CharField(max_length = 50, blank=False, null = False)	
    NOMBRE = models.CharField(max_length = 50, blank=False, null = False)	
    LATITUD = models.CharField(max_length = 50, blank=False, null = False)	
    LONGITUD = models.CharField(max_length = 50, blank=False, null = False)	
    ESTADO = models.CharField(max_length = 50, blank=False, null = False)	
    MUNICIPIO = models.CharField(max_length = 50, blank=False, null = False)	
    MERCADO	= models.TextField(max_length = 50, blank=False, null = False)	
    MERCADO_FO = models.TextField(max_length = 50, blank=False, null = False)	
    REGION_CELULAR = models.TextField(max_length = 50, blank=False, null = False)	
    AGREGADOR = models.TextField(max_length = 50, blank=False, null = False)	
    AÑO	= models.TextField(max_length = 50, blank=False, null = False)	
    PROYECTO = models.TextField(max_length = 50, blank=False, null = False)	
    TOPOLOGIA = models.TextField(max_length = 50, blank=False, null = False)	
    SEGMENTO_IPBH = models.TextField(max_length = 50, blank=False, null = False)	
    STATUS = models.TextField(max_length = 50, blank=False, null = False)
    TX_FO = models.TextField(max_length = 50, blank=False, null = False)	
    class Meta:
        verbose_name = 'Fibra'
        verbose_name_plural = 'Fibras'
        db_table = "fibraoptica"

# class Filtro_FO(models.Model):
#     ID_ATT_F = models.TextField()	
#     TX = models.TextField()	
#     TX_GRUPOS = models.TextField()	
#     TX_DETALLE = models.TextField()	
#     CONTROL = models.TextField()	
#     FECHA = models.TextField()	
#     POC	= models.TextField()	
#     OBSERVACIONES = models.TextField()	
#     MERCADO = models.TextField()	
#     AÑO	= models.IntegerField()	
#     PROYECTO = models.TextField()	
#     TOPOLOGIA = models.TextField()	
#     SEGMENTO_IPBH = models.TextField()	
#     STATUS = models.TextField()	

#     class Meta:
#         db_table = "tb1_fibraoptica"

class AGG(models.Model):
    ATT_ID_A = models.TextField(max_length = 50, blank=False, null = False)		
    TX_A = models.TextField(max_length = 50, blank=False, null = False)	
    TX_GRUPOS_A = models.TextField(max_length = 50, blank=False, null = False)	
    TX_DETALLE_A = models.TextField(max_length = 50, blank=False, null = False)	
    CONTROL = models.TextField(max_length = 50, blank=False, null = False)	
    FECHA = models.TextField(max_length = 50, blank=False, null = False)	
    POC	= models.TextField(max_length = 50, blank=False, null = False)	
    OBSERVACIONES = models.TextField(max_length = 50, blank=False, null = False)	
    TRACKER	= models.TextField(max_length = 50, blank=False, null = False)	
    ID_ATT = models.TextField(max_length = 50, blank=False, null = False)	
    NOMBRE = models.TextField(max_length = 50, blank=False, null = False)	
    LATITUD	= models.TextField(max_length = 50, blank=False, null = False)	
    LONGITUD = models.TextField(max_length = 50, blank=False, null = False)	
    ESTADO = models.TextField(max_length = 50, blank=False, null = False)	
    MUNICIPIO = models.TextField(max_length = 50, blank=False, null = False)	
    MERCADO	= models.TextField(max_length = 50, blank=False, null = False)	
    MERCADO_FO = models.TextField(max_length = 50, blank=False, null = False)	
    REGION_CELULAR = models.TextField(max_length = 50, blank=False, null = False)	
    AGREGADOR = models.TextField(max_length = 50, blank=False, null = False)	
    AÑO	= models.TextField(max_length = 50, blank=False, null = False)	
    PROYECTO = models.TextField(max_length = 50, blank=False, null = False)	
    TOPOLOGIA = models.TextField(max_length = 50, blank=False, null = False)	
    SEGMENTO_IPBH = models.TextField(max_length = 50, blank=False, null = False)	
    STATUS = models.TextField(max_length = 50, blank=False, null = False)	
    TX_FO = models.TextField(max_length = 50, blank=False, null = False)	

    class Meta:
        db_table = 'agregadores'      

# class Filtro_AGG(models.Model):
#     ATT_ID_A = models.TextField(max_length = 50, blank=False, null = False)		
#     TX = models.TextField(max_length = 50, blank=False, null = False)	
#     TX_GRUPOS_AGG = models.TextField(max_length = 50, blank=False, null = False)	
#     TX_DETALLE_AGG = models.TextField(max_length = 50, blank=False, null = False)	
#     CONTROL = models.TextField(max_length = 50, blank=False, null = False)	
#     FECHA = models.TextField(max_length = 50, blank=False, null = False)	
#     POC	= models.TextField(max_length = 50, blank=False, null = False)	
#     OBSERVACIONES = models.TextField(max_length = 50, blank=False, null = False)	
#     MERCADO = models.TextField(max_length = 50, blank=False, null = False)	
#     AGREGADOR = models.TextField(max_length = 50, blank=False, null = False)	
#     AÑO_F = models.TextField(max_length = 50, blank=False, null = False)	
#     PROYECTO = models.TextField(max_length = 50, blank=False, null = False)	
#     TOPOLOGIA = models.TextField(max_length = 50, blank=False, null = False)	
#     SEGMENTO_IPBH = models.TextField(max_length = 50, blank=False, null = False)	
#     STATUS = models.TextField(max_length = 50, blank=False, null = False)	

#     class Meta:
#         db_table = 'tb1_agregadores'        

class Proyeccion(models.Model):
    ID_ATT_P = models.TextField(max_length = 50, blank=False, null = False)	
    TX = models.TextField(max_length = 50, blank=False, null = False)	
    TX_GRUPOS_PROYECCION = models.TextField(max_length = 50, blank=False, null = False)	
    TX_DETALLE_PROYECCION = models.TextField(max_length = 50, blank=False, null = False)	
    CONTROL = models.TextField(max_length = 50, blank=False, null = False)	
    AÑO_PROYECCION = models.TextField(max_length = 50, blank=False, null = False)	
    FECHA = models.TextField(max_length = 50, blank=False, null = False)	
    POC	= models.TextField(max_length = 50, blank=False, null = False)
    OBSERVACIONES = models.TextField(max_length = 50, blank=False, null = False)	
    TRACKER = models.TextField(max_length = 50, blank=False, null = False)	
    ATT_ID = models.TextField(max_length = 50, blank=False, null = False)	
    NOMBRE = models.TextField(max_length = 50, blank=False, null = False)	
    LATITUD = models.TextField(max_length = 50, blank=False, null = False)	
    LONGITUD = models.TextField(max_length = 50, blank=False, null = False)	
    ESTADO = models.TextField(max_length = 50, blank=False, null = False)	
    MUNICIPIO = models.TextField(max_length = 50, blank=False, null = False)
    MERCADO	= models.TextField(max_length = 50, blank=False, null = False)
    MERCADO_FO = models.TextField(max_length = 50, blank=False, null = False)
    REGION_CELULAR = models.TextField(max_length = 50, blank=False, null = False)
    AGREGADOR = models.TextField(max_length = 50, blank=False, null = False)
    AÑO	= models.TextField(max_length = 50, blank=False, null = False)
    PROYECTO = models.TextField(max_length = 50, blank=False, null = False)
    TOPOLOGIA = models.TextField(max_length = 50, blank=False, null = False)
    SEGMENTO_IPBH = models.TextField(max_length = 50, blank=False, null = False)
    STATUS = models.TextField(max_length = 50, blank=False, null = False)
    TX_F = models.TextField(max_length = 50, blank=False, null = False)

    class Meta:
        db_table = 'proyeccion'

# class FiltroProyeccion(models.Model):
#     ID_ATT_P = models.TextField()	
#     TX = models.TextField()	
#     TX_GRUPOS_PROYECCION = models.TextField()	
#     TX_DETALLE_PROYECCION= models.TextField()	
#     CONTROL = models.TextField()	
#     AÑO_PROYECCION = models.TextField()	
#     FECHA = models.TextField()	
#     POC	= models.TextField()
#     OBSERVACIONES = models.TextField()	
#     MERCADO_FO = models.TextField()
#     AÑO	= models.TextField()
#     PROYECTO = models.TextField()
#     TOPOLOGIA = models.TextField()
#     STATUS = models.TextField()

#     class Meta:
#         db_table = 'tb1_proyeccion'

class Migracion(models.Model):
    ID_ATT_M = models.TextField(max_length = 50, blank=False, null = False)	
    ORIGEN_TX = models.TextField(max_length = 50, blank=False, null = False)
    TX_GRUPOS = models.TextField(max_length = 50, blank=False, null = False)
    TX_DETALLE = models.TextField(max_length = 50, blank=False, null = False)
    CONTROL = models.TextField(max_length = 50, blank=False, null = False)
    FECHA = models.TextField(max_length = 50, blank=False, null = False)
    POC	= models.TextField(max_length = 50, blank=False, null = False)
    OBSERVACIONES = models.TextField(max_length = 50, blank=False, null = False)
    ID_PANDA = models.TextField(max_length = 50, blank=False, null = False)
    ID_ATT = models.TextField(max_length = 50, blank=False, null = False)
    SITE_NAME = models.TextField(max_length = 50, blank=False, null = False)
    MARKET = models.TextField(max_length = 50, blank=False, null = False)
    PROYECTO = models.TextField(max_length = 50, blank=False, null = False)
    REAL_MIGRACION = models.TextField(max_length = 50, blank=False, null = False)
    SCOPE = models.TextField(max_length = 50, blank=False, null = False)
    PANDA = models.TextField(max_length = 50, blank=False, null = False)
    STATUS = models.TextField(max_length = 50, blank=False, null = False)
    TX_TYPE	= models.TextField(max_length = 50, blank=False, null = False)
    ATT_ID = models.TextField(max_length = 50, blank=False, null = False)
    LATITUD	= models.TextField(max_length = 50, blank=False, null = False)
    LONGITUD = models.TextField(max_length = 50, blank=False, null = False)
    ESTADO = models.TextField(max_length = 50, blank=False, null = False)
    MUNICIPIO = models.TextField(max_length = 50, blank=False, null = False)
    MERCADO	= models.TextField(max_length = 50, blank=False, null = False)
    REGION_CELULAR = models.TextField(max_length = 50, blank=False, null = False)
    CLASIFICACION = models.TextField(max_length = 50, blank=False, null = False)
    CONTROL_DE_CAMBIOS_RAN = models.TextField(max_length = 50, blank=False, null = False)
    class Meta:
        db_table = 'migracion'  

class MW(models.Model):
    ATT_ID_MW = models.TextField(max_length = 50, blank=False, null = False)
    TX_MW = models.TextField(max_length = 50, blank=False, null = False)  
    TX_GRUPOS_MW = models.TextField(max_length = 50, blank=False, null = False)   
    TX_DETALLE_MW = models.TextField(max_length = 50, blank=False, null = False)  
    CONROL = models.TextField(max_length = 50, blank=False, null = False) 
    FECHA = models.TextField(max_length = 50, blank=False, null = False)  
    POC = models.TextField(max_length = 50, blank=False, null = False)    
    OBSERVACIONES=models.TextField(max_length = 50, blank=False, null = False)  
    NOMBRE=models.TextField(max_length = 50, blank=False, null = False) 
    LATITUD=models.TextField(max_length = 50, blank=False, null = False)    
    LONGITUD=models.TextField(max_length = 50, blank=False, null = False)   
    ESTADO=models.TextField(max_length = 50, blank=False, null = False) 
    MUNICIPIO=models.TextField(max_length = 50, blank=False, null = False)  
    MERCADO=models.TextField(max_length = 50, blank=False, null = False)    
    REGION_CELULAR=models.TextField(max_length = 50, blank=False, null = False) 
    CONTROL_DE_CAMBIOS_RAN=models.TextField(max_length = 50, blank=False, null = False) 
    PROYECTO_MIGRADOS=models.TextField(max_length = 50, blank=False, null = False)  
    REAL_MIGRACION=models.TextField(max_length = 50, blank=False, null = False) 
    TX_ORIGEN=models.TextField(max_length = 50, blank=False, null = False)  
    MEDIO_TX_GRUPOS=models.TextField(max_length = 50, blank=False, null = False)    
    TX_DETALLE=models.TextField(max_length = 50, blank=False, null = False) 
    PANDA=models.TextField(max_length = 50, blank=False, null = False)  
    STATUS=models.TextField(max_length = 50, blank=False, null = False) 
    TX_TYPE=models.TextField(max_length = 50, blank=False, null = False)    
    CAPACIDAD_1G=models.TextField(max_length = 50, blank=False, null = False)   
    SITIO_A=models.TextField(max_length = 50, blank=False, null = False)    
    SITIO_B=models.TextField(max_length = 50, blank=False, null = False)    
    ENLACE=models.TextField(max_length = 50, blank=False, null = False) 
    TECNOLOGIA=models.TextField(max_length = 50, blank=False, null = False) 
    AGREGADOR_GRUPO=models.TextField(max_length = 50, blank=False, null = False)    
    AGREGADOR_DETALLE=models.TextField(max_length = 50, blank=False, null = False)  
    AGREGADOR=models.TextField(max_length = 50, blank=False, null = False)  
    TRACKER=models.TextField(max_length = 50, blank=False, null = False)    
    ATTID_1=models.TextField(max_length = 50, blank=False, null = False)  
    SITE_A =models.TextField(max_length = 50, blank=False, null = False)   
    SITE_B=models.TextField(max_length = 50, blank=False, null = False)    
    LINK=models.TextField(max_length = 50, blank=False, null = False)   
    AGREGADOR=models.TextField(max_length = 50, blank=False, null = False)  
    SITE_1=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_2=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_3=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_4=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_5=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_6=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_7=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_8=models.TextField(max_length = 50, blank=False, null = False) 
    SITE_9 = models.TextField(max_length = 50, blank=False, null = False) 
    SITE_10 = models.TextField(max_length = 50, blank=False, null = False)    
    SITIOS_CARGA = models.TextField(max_length = 50, blank=False, null = False)   
    TIPO = models.TextField(max_length = 50, blank=False, null = False)   
    ATTID_2 = models.TextField(max_length = 50, blank=False, null = False)  
    TECNOLOGIA_ACTUAL = models.TextField(max_length = 50, blank=False, null = False)  
    CAPACIDAD_MBPS = models.TextField(max_length = 50, blank=False, null = False)   
    UTILIZACION_MBPS = models.TextField(max_length = 50, blank=False, null = False) 
    FLAG_H = models.TextField(max_length = 50, blank=False, null = False) 
    NUMERO_DE_CERTIFICADO = models.TextField(max_length = 50, blank=False, null = False)  
    NUMERO_DE_LINK = models.TextField(max_length = 50, blank=False, null = False) 
    IDENTIFICADOR_CERTIFICADO = models.TextField(max_length = 50, blank=False, null = False)  
    CONCESIONARIO = models.TextField(max_length = 50, blank=False, null = False)  
    RESPONSABLE_CONS = models.TextField(max_length = 50, blank=False, null = False)   
    DIRECCION_CONS = models.TextField(max_length = 50, blank=False, null = False) 
    TELEFONO_CONS = models.TextField(max_length = 50, blank=False, null = False)  
    E_MAIL_CONS = models.TextField(max_length = 50, blank=False, null = False)    
    USUARIO_FINAL = models.TextField(max_length = 50, blank=False, null = False)  
    RESPONSABLE_US = models.TextField(max_length = 50, blank=False, null = False) 
    DIRECCION_US = models.TextField(max_length = 50, blank=False, null = False)   
    TELEFONO_US = models.TextField(max_length = 50, blank=False, null = False)    
    E_MAIL_US = models.TextField(max_length = 50, blank=False, null = False)  
    FECHA_SOLICITUD = models.TextField(max_length = 50, blank=False, null = False)    
    FECHA_CONSTANCIA = models.TextField(max_length = 50, blank=False, null = False)  
    FECHA_DE_CANCELACION = models.TextField(max_length = 50, blank=False, null = False)   
    MOTIVO = models.TextField(max_length = 50, blank=False, null = False) 
    NOMBRE_A = models.TextField(max_length = 50, blank=False, null = False)   
    DOMICILIO_A = models.TextField(max_length = 50, blank=False, null = False)    
    CIUDAD_A = models.TextField(max_length = 50, blank=False, null = False)   
    CLAVE_ESTADO_A = models.TextField(max_length = 50, blank=False, null = False) 
    LATITUD_GRAD_A = models.TextField(max_length = 50, blank=False, null = False) 
    LATITUD_MIN_A = models.TextField(max_length = 50, blank=False, null = False)  
    LATITUD_SEG_A = models.TextField(max_length = 50, blank=False, null = False)  
    LONGITUD_GRAD_A = models.TextField(max_length = 50, blank=False, null = False)    
    LONGITUD_MIN_A = models.TextField(max_length = 50, blank=False, null = False) 
    LONGITUD_SEG_A = models.TextField(max_length = 50, blank=False, null = False) 
    ASNM_A = models.TextField(max_length = 50, blank=False, null = False) 
    AZIMUT_A = models.TextField(max_length = 50, blank=False, null = False)   
    NOMBRE_B = models.TextField(max_length = 50, blank=False, null = False)   
    DOMICILIO_B = models.TextField(max_length = 50, blank=False, null = False)    
    CIUDAD_B = models.TextField(max_length = 50, blank=False, null = False)   
    CLAVE_ESTADO_B = models.TextField(max_length = 50, blank=False, null = False) 
    LATITUD_GRAD_B = models.TextField(max_length = 50, blank=False, null = False) 
    LATITUD_MIN_B = models.TextField(max_length = 50, blank=False, null = False)  
    LATITUD_SEG_B = models.TextField(max_length = 50, blank=False, null = False)  
    LONGITUD_GRAD_B = models.TextField(max_length = 50, blank=False, null = False)    
    LONGITUD_MIN_B = models.TextField(max_length = 50, blank=False, null = False) 
    LONGITUD_SEG_B = models.TextField(max_length = 50, blank=False, null = False) 
    ASNM_B = models.TextField(max_length = 50, blank=False, null = False) 
    AZIMUT_B = models.TextField(max_length = 50, blank=False, null = False)   
    LONGITUD_ENLACE = models.TextField(max_length = 50, blank=False, null = False)    
    BANDA_FRECUENCIA = models.TextField(max_length = 50, blank=False, null = False)   
    FRECUENCIA_TX = models.TextField(max_length = 50, blank=False, null = False)  
    FRECUENCIA_RX = models.TextField(max_length = 50, blank=False, null = False)  
    MARCA_RADIO = models.TextField(max_length = 50, blank=False, null = False)    
    MODELO_RADIO = models.TextField(max_length = 50, blank=False, null = False)   
    MODULACION = models.TextField(max_length = 50, blank=False, null = False) 
    EMISION = models.TextField(max_length = 50, blank=False, null = False)    
    ANCHO_BANDA = models.TextField(max_length = 50, blank=False, null = False)    
    TX_PLANNED = models.TextField(max_length = 50, blank=False, null = False)
    SEPARACION_CANAL = models.TextField(max_length = 50, blank=False, null = False)   
    SUB_BANDA_OP = models.TextField(max_length = 50, blank=False, null = False)   
    SEPARACION_DUPLEX = models.TextField(max_length = 50, blank=False, null = False)  
    UMBRA_RECEPCION = models.TextField(max_length = 50, blank=False, null = False)    
    TASA_DE_BITS_UMBRAL = models.TextField(max_length = 50, blank=False, null = False)    
    PIRE = models.TextField(max_length = 50, blank=False, null = False)   
    PIRE_A = models.TextField(max_length = 50, blank=False, null = False) 
    PIRE_B = models.TextField(max_length = 50, blank=False, null = False) 
    VELOCIDAD_TX = models.TextField(max_length = 50, blank=False, null = False)   
    CAPACIDAD_CANALES = models.TextField(max_length = 50, blank=False, null = False)  
    HOMOLOGACION_EQUIPO = models.TextField(max_length = 50, blank=False, null = False)    
    CONFIGURACION_ENLACE = models.TextField(max_length = 50, blank=False, null = False)   
    ANTENA_TIPO_A = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_MARCA_A = models.TextField(max_length = 50, blank=False, null = False) 
    ANTENA_MODELO_A = models.TextField(max_length = 50, blank=False, null = False)    
    ANTENA_DIAMETRO_A = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_GANANCIA_A = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_POLARIZACION_A = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_ANGULO_ABERTURA_A = models.TextField(max_length = 50, blank=False, null = False)   
    ANTENA_ANGULO_ELEVACION_A = models.TextField(max_length = 50, blank=False, null = False)  
    MODELO_RADIO_B = models.TextField(max_length = 50, blank=False, null = False) 
    ANTENA_TIPO_B = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_MARCA_B = models.TextField(max_length = 50, blank=False, null = False) 
    ANTENA_MODELO_B = models.TextField(max_length = 50, blank=False, null = False)    
    ANTENA_DIAMETRO_B = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_GANANCIA_B = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_POLARIZACION_B = models.TextField(max_length = 50, blank=False, null = False)  
    ANTENA_ANGULO_ABERTURA_B = models.TextField(max_length = 50, blank=False, null = False)   
    ANTENA_ANGULO_ELEVACION_B = models.TextField(max_length = 50, blank=False, null = False)  
    LINEA_MARCA_A = models.TextField(max_length = 50, blank=False, null = False)  
    LINEA_TIPO_A = models.TextField(max_length = 50, blank=False, null = False)   
    LINEA_LONGITUD_A = models.TextField(max_length = 50, blank=False, null = False)   
    LINEA_ATENUACION_A = models.TextField(max_length = 50, blank=False, null = False) 
    OTRAS_PERDIDAS_TX_A = models.TextField(max_length = 50, blank=False, null = False)    
    OTRAS_PERDIDAS_RX_A = models.TextField(max_length = 50, blank=False, null = False)    
    LINEA_MARCA_B = models.TextField(max_length = 50, blank=False, null = False)  
    LINEA_TIPO_B = models.TextField(max_length = 50, blank=False, null = False)   
    LINEA_LONGITUD_B = models.TextField(max_length = 50, blank=False, null = False)   
    LINEA_ATENUACION_B = models.TextField(max_length = 50, blank=False, null = False) 
    OTRAS_PERDIDAS_TX_B = models.TextField(max_length = 50, blank=False, null = False)    
    OTRAS_PERDIDAS_RX_B = models.TextField(max_length = 50, blank=False, null = False)    
    EDIFICIO_ALTURA_A = models.TextField(max_length = 50, blank=False, null = False)  
    TORRE_ALTURA_A = models.TextField(max_length = 50, blank=False, null = False) 
    TORRE_ANTENA_ALTURA_A = models.TextField(max_length = 50, blank=False, null = False)  
    TORRE_TIPO_A = models.TextField(max_length = 50, blank=False, null = False)   
    EDIFICIO_ALTURA_B = models.TextField(max_length = 50, blank=False, null = False) 
    TORRE_ALTURA_B = models.TextField(max_length = 50, blank=False, null = False) 
    TORRE_ANTENA_ALTURA_B = models.TextField(max_length = 50, blank=False, null = False)  
    TORRE_TIPO_B = models.TextField(max_length = 50, blank=False, null = False)   
    POT_TX_A = models.TextField(max_length = 50, blank=False, null = False)   
    RX_PLANNED_A = models.TextField(max_length = 50, blank=False, null = False)   
    POTE_TX_B = models.TextField(max_length = 50, blank=False, null = False)  
    RX_PLANNED_B = models.TextField(max_length = 50, blank=False, null = False)   
    NO_CHANNEL = models.TextField(max_length = 50, blank=False, null = False) 
    CHANNEL_ID_A = models.TextField(max_length = 50, blank=False, null = False)  
    CHANNEL_ID_B = models.TextField(max_length = 50, blank=False, null = False)  
    OBSERVACIONES = models.TextField(max_length = 50, blank=False, null = False) 
    CONFIGURACION = models.TextField(max_length = 50, blank=False, null = False)  
    PROYECTO = models.TextField(max_length = 50, blank=False, null = False)   
    SOLICITUD = models.TextField(max_length = 50, blank=False, null = False)  
    ELLIPSE = models.TextField(max_length = 50, blank=False, null = False)    
    GOOGLE = models.TextField(max_length = 50, blank=False, null = False) 
    ORDEN_DE_TRABAJO = models.TextField(max_length = 50, blank=False, null = False)   
    CONTRATISTA = models.TextField(max_length = 50, blank=False, null = False)    
    PROTOCOLO_DE_RECEPCION = models.TextField(max_length = 50, blank=False, null = False) 
    RX_MED_A = models.TextField(max_length = 50, blank=False, null = False)
    RX_MED_B = models.TextField(max_length = 50, blank=False, null = False)
    GESTION = models.TextField(max_length = 50, blank=False, null = False)
    IPLOCAL = models.TextField(max_length = 50, blank=False, null = False)
    IP_REMOTO = models.TextField(max_length = 50, blank=False, null = False)
    NO_SERIE_IDU_LOCAL = models.TextField(max_length = 50, blank=False, null = False)
    NO_SERIE_ODU_LOCAL = models.TextField(max_length = 50, blank=False, null = False)
    NO_SERIE_IDU_REMOTO = models.TextField(max_length = 50, blank=False, null = False)
    NO_SERIE_ODU_REMOTO = models.TextField(max_length = 50, blank=False, null = False)    
    OBSERVACIONES = models.TextField(max_length = 50, blank=False, null = False)
    INGENIERIA  = models.TextField(max_length = 50, blank=False, null = False)
    DESMONTAJES = models.TextField(max_length = 50, blank=False, null = False)    
    FECHA = models.TextField(max_length = 50, blank=False, null = False)
    RESPONSABLE = models.TextField(max_length = 50, blank=False, null = False)         
    class Meta:
        db_table = 'microondas'    

class Carrier(models.Model):
    ID_ATT_C = models.TextField(max_length = 50, blank=False, null = False)
    TX = models.TextField(max_length = 50, blank=False, null = False)
    TX_GRUPOS = models.TextField(max_length = 50, blank=False, null = False)
    TX_DETALLE = models.TextField(max_length = 50, blank=False, null = False)
    CONTROL = models.TextField(max_length = 50, blank=False, null = False)
    FECHA_ALTA_BAJA = models.TextField(max_length = 50, blank=False, null = False)
    POC = models.TextField(max_length = 50, blank=False, null = False)
    OBSERVACIONES = models.TextField(max_length = 50, blank=False, null = False)
    TX_CARRIER = models.TextField(max_length = 50, blank=False, null = False)
    PROYECTO_FO = models.TextField(max_length = 50, blank=False, null = False)	
    SEGUNDO_PUERTO_HABILITADO = models.TextField(max_length = 50, blank=False, null = False)
    CID_CARRIER = models.TextField(max_length = 50, blank=False, null = False)
    REGION = models.TextField(max_length = 50, blank=False, null = False)
    MERCADO = models.TextField(max_length = 50, blank=False, null = False)
    PUNTA_A_NAMING_CONVECTION = models.TextField(max_length = 50, blank=False, null = False)
    PUNTA_A_ID_SITIO = models.TextField(max_length = 50, blank=False, null = False)
    PUNTA_A_NOMBRE_SITIO = models.TextField(max_length = 50, blank=False, null = False)
    LATITUD_PUNTA_A = models.TextField(max_length = 50, blank=False, null = False)
    LONGITUD_PUNTA_A = models.TextField(max_length = 50, blank=False, null = False)
    PUNTA_B_NAMING_CONVECTION = models.TextField(max_length = 50, blank=False, null = False)
    PUNTA_B_ID_SITIO = models.TextField(max_length = 50, blank=False, null = False)
    PUNTA_B_NOMBRE_SITIO = models.TextField(max_length = 50, blank=False, null = False)
    LATITUD_PUNTA_B = models.TextField(max_length = 50, blank=False, null = False)
    LONGITUD_PUNTA_B = models.TextField(max_length = 50, blank=False, null = False)
    CARRIER	= models.TextField(max_length = 50, blank=False, null = False)
    TIPO_ENLACE = models.TextField(max_length = 50, blank=False, null = False)
    PROYECTO_PRINCIPAL = models.TextField(max_length = 50, blank=False, null = False)
    FASE = models.TextField(max_length = 50, blank=False, null = False)
    CAPACIDAD_MBPS = models.TextField(max_length = 50, blank=False, null = False)
    ESTATUS = models.TextField(max_length = 50, blank=False, null = False)
    TRACKER = models.TextField(max_length = 50, blank=False, null = False)
    ATT_ID = models.TextField(max_length = 50, blank=False, null = False)
    NOMBRE = models.TextField(max_length = 50, blank=False, null = False)
    CONTROL_DE_CAMBIOS_RAN = models.TextField(max_length = 50, blank=False, null = False)
    BASE_ORIGEN_TX = models.TextField(max_length = 50, blank=False, null = False)
    GRUPOS_MEDIO_TX = models.TextField(max_length = 50, blank=False, null = False)
    TX_DETALLE_2 = models.TextField(max_length = 50, blank=False, null = False)
    BASE_ORIGEN_PROYECCION = models.TextField(max_length = 50, blank=False, null = False)
    class Meta:
        db_table = 'carrier' 

class Pon(models.Model):
    ID_ATT_PON = models.TextField() 	
    TX_PON = models.TextField()	
    TX_GRUPOS_PON = models.TextField()	
    TX_DETALLE_PON = models.TextField()	
    CONTROL_PON = models.TextField()	
    FECHA_PON = models.TextField()	
    POC_PON = models.TextField()	
    OBSERVACIONES_PON = models.TextField()	
    REGION = models.TextField()	
    CIUDAD = models.TextField()	
    OLT_NAME_1 = models.TextField()	
    OLT_ATT_ID = models.TextField()	
    OLT_IP = models.TextField()	
    OLT_NAME_2 = models.TextField()	
    OLT_TYPE = models.TextField()	
    FRAME_ID = models.TextField()	
    SLOT_ID = models.TextField()	
    PORT_ID = models.TextField()	
    ONU_ID = models.TextField()	
    ONT_NAME = models.TextField()	
    ONT_OLD_NAME = models.TextField()	
    SITE_ID = models.TextField()	
    ID_ATT = models.TextField()	
    CON_SIN_SERVICIOS = models.TextField()	
    ONU_IP = models.TextField()	
    ONT_TYPE = models.TextField()	
    ONU_TYPE = models.TextField()	
    SN_MAC = models.TextField()	
    VENDOR = models.TextField()	
    RUNNIG_STATUS= models.TextField()	
    OPERATION_STATUS= models.TextField()
    class Meta:
        db_table = 'pon' 

class Panda(models.Model):
    TRACKER = models.TextField()	
    NAMING_CONVENTION = models.TextField()	
    SITE_NAME = models.TextField()	
    PLACEMENT = models.TextField()	
    PROJECT = models.TextField()
    ID_LOCATION	= models.TextField()
    ID_SITE	= models.TextField()
    PANDA_CODE = models.TextField()
    SITE_TYPE = models.TextField()
    STATUS = models.TextField()
    MILESTONE = models.TextField()
    BATCH = models.TextField()
    MARKET = models.TextField()
    CLUSTER	= models.TextField()
    EQUIPMENT = models.TextField()
    YEAR_PLAN = models.TextField()
    ISSUE_TYPE = models.TextField()
    OWNER = models.TextField()
    OWNER_ID = models.TextField()
    CANDIDATE = models.TextField()
    INSTALL_TYPE = models.TextField()
    TOWER_TYPE = models.TextField()
    BUILDING_HT	= models.TextField()
    TOWER_HT = models.TextField()
    TX_TYPE	= models.TextField()
    LATITUDE = models.TextField()
    LONGITUDE = models.TextField()
    MUNICIPALITY = models.TextField()
    STATE = models.TextField()
    CONTAINER_TYPE = models.TextField()
    SOLUTION_TYPE = models.TextField()
    PROJECT_RELEASED_1 = models.TextField()											
    PROJECT_RELEASED_2= models.TextField()											
    PROJECT_RELEASED_3 = models.TextField()											
    PROJECT_RELEASED_4 = models.TextField()											
    PROJECT_RELEASED_5 = models.TextField()											
    PROJECT_RELEASED_6= models.TextField()											
    PROJECT_RELEASED_7= models.TextField()											
    PROJECT_RELEASED_8= models.TextField()											
    PROJECT_RELEASED_9= models.TextField()											
    PROJECT_RELEASED_10= models.TextField()											
    PROJECT_RELEASED_11= models.TextField()											
    PROJECT_RELEASED_12= models.TextField()											
    PROJECT_RELEASED_13= models.TextField()											
    PROJECT_RELEASED_14= models.TextField()											
    PROJECT_RELEASED_15= models.TextField()											
    PROJECT_RELEASED_16= models.TextField()											
    PROJECT_RELEASED_17= models.TextField()											
    class Meta:
        db_table = 'panda'

class Tellus(models.Model):
    SYSTEM_ID = models.TextField()	
    SITE = models.TextField()	
    NAME = models.TextField()
    GSM	= models.TextField()
    UMTS = models.TextField()
    LTE	= models.TextField()
    HIERARCHY = models.TextField()
    COLLOS = models.TextField()
    CVE_INSTALL_TYPE = models.TextField()	
    OPERATIVE_STATUS = models.TextField()	
    DATE_ONAIR = models.TextField()	
    OWNER = models.TextField()	
    ADDRESS = models.TextField()	
    MUNICIPALITY = models.TextField()
    STATE_NAME = models.TextField()	
    MARKET = models.TextField()	
    LATITUDE = models.TextField()	
    LONGITUDE = models.TextField()	
    CELL_REGION = models.TextField()	
    CELLOWNER = models.TextField()	
    CELLOWNER_TELEPHONE = models.TextField()	
    CELLOWNER_EMAIL = models.TextField()	
    COORDINATOR = models.TextField()	
    COORDINATOR_TELEPHONE = models.TextField()	
    COORDINATOR_EMAIL = models.TextField()	
    MANAGER = models.TextField()	
    MANAGER_TELEPHONE = models.TextField()	
    MANAGER_EMAIL = models.TextField()	
    DIRECTOR = models.TextField()	
    DIRECTOR_TELEPHONE = models.TextField()	
    DIRECTOR_EMAIL = models.TextField()	
    COORDINATION = models.TextField()	
    MANAGEMENT = models.TextField()	
    REGION = models.TextField()
    class Meta:
            db_table = 'tellus'            

class CapacidadManual(models.Model):
    ID_ATT	= models.TextField()
    TX	= models.TextField()
    TX_GRUPOS_MANUAL = models.TextField()	
    TX_DETALLE_MANUAL = models.TextField()	
    CONTROL	= models.TextField()
    FECHA = models.TextField()	
    POC = models.TextField()	
    OBSERVACIONES = models.TextField()	
    TRACKER = models.TextField()	
    ATT_ID = models.TextField()	
    NOMBRE = models.TextField()	
    LATITUD = models.TextField()	
    LONGITUD = models.TextField()	
    ESTADO = models.TextField()	
    MUNICIPIO = models.TextField()	
    MERCADO = models.TextField()	
    REGION_CELULAR = models.TextField()	
    REGION = models.TextField()	
    VENDOR = models.TextField()	
    COBERTURA = models.TextField()	
    TIPO = models.TextField()	
    PROYECTO = models.TextField()	
    CLASIFICACION = models.TextField()	
    CONTROL_CAMBIOS_RAN = models.TextField()	
    BASE_ORIGEN_TX = models.TextField()	
    GRUPOS_MEDIO_TX = models.TextField()	
    TX_DETALLE = models.TextField()	
    CAPACIDAD = models.TextField()	
    CONTROL = models.TextField()
    class Meta:
            db_table = 'capacidadManual'    

# class Semaforos(models.Model):
#     AGGREGATOR = models.TextField()
#     SITE_1 = models.TextField()
#     SITE_2 = models.TextField()
#     SITE_3 = models.TextField()
#     SITE_4 = models.TextField()
#     SITE_5 = models.TextField()
#     SITE_6 = models.TextField()
#     SITE_7 = models.TextField()
#     SITE_8 = models.TextField()
#     SITE_9 = models.TextField()
#     SITE_10 = models.TextField()
#     SITE_ID	= models.TextField()
#     ATTID = models.TextField()
#     LINK = models.TextField()
#     TX_ACTUAL = models.TextField()
#     SITIOS_QUE_CARGA = models.TextField()
#     TECNOLOGIA_ACTUAL = models.TextField()
#     CAPACIDAD_MBPS = models.TextField()
#     CONFIGURACION = models.TextField()
#     ANCHO_DE_BANDA = models.TextField()
#     TX_A = models.TextField()
#     TX_B = models.TextField()
#     UTILIZACION_MBPS_1 = models.TextField()
#     PORCENTAJE_UTILIZACION_PICOS_MAXIMOS = models.TextField()
#     FLAG_H = models.TextField()
#     UTILIZACION_MBPS_2 = models.TextField()
#     PORCENTAJE_UTILIZACION_PICOS_MAXIMOS_2 = models.TextField()
#     FLAG_V = models.TextField()
#     SITIOS = models.TextField()
#     SITE_FLOATING_MERCADO = models.TextField()
#     LINK_FLOATING_2023_MBPS	= models.TextField()
#     FLAG_FLOATING_2023_MBPS	 = models.TextField()
#     PRIORIDAD_TAC_FLOATING_2023_MBPS = models.TextField()
#     SALUD_FLOATING_2023_MBPS = models.TextField()
#     PUNTO_AFECTACION_FLOATING_2023_MBPS	= models.TextField()
#     SITE_FLOATING_MUNICIPIO	= models.TextField()
#     LINK_FLOATING_2024_MBPS	= models.TextField()
#     FLAG_FLOATING_2024_MBPS	= models.TextField()
#     PRIORIDAD_TAC_FLOATING_2024_MBPS = models.TextField()
#     SALUD_FLOATING_2024_MBPS = models.TextField()
#     PUNTO_DE_AFECTACION_FLOATING_2024_MBPS = models.TextField()
#     class Meta:
#             db_table = 'semaforos'  

# class NOC(models.Model):
#    VENDOR = models.TextField()	
#    IP_ADDRESS = models.TextField()	
#    PREFIX_LENGTH = models.TextField()	
#    INTERFACE_NAME = models.TextField()	
#    ID_SITE_DEVICE_NAME = models.TextField()	
#    DEVICE_NAME = models.TextField()	
#    SITE_ID = models.TextField()	
#    LAGPORT = models.TextField()	
#    WORK_IP = models.TextField()	
#    WORK_IP2 = models.TextField()	
#    WORK_IP3 = models.TextField()	
#    LAG_CONFIGURATED_SPEED = models.TextField()	
#    LAG_CLASS = models.TextField()	
#    WORK_SPEED= models.TextField()	
#    TO = models.TextField()	
#    IP_ADDRESS_P2P = models.TextField()	
#    PREFIX_LENGTH_P2P = models.TextField()	
#    SITE_ID_P2P	= models.TextField()
#    ID_SITE_NAME_P2P	= models.TextField()
#    SITE_NAME_P2P= models.TextField()	
#    INTERFACE_NAME_P2P= models.TextField()	
#    LAGPORT_P2P= models.TextField()	
#    CONFIGURATED_SPEED_P2P= models.TextField()	
#    LAGG_CLASS_P2P= models.TextField()	
#    OPERATIONAL_SPEED_KBPS_P2P= models.TextField()	
#    VENDOR_P2P= models.TextField()

#    class Meta:
#             db_table = 'tb1_noc'  

# class BaseSinTX(models.Model):                    
#     ID_ATT= models.TextField()	
#     TX	= models.TextField()
#     TX_GRUPOS_MANUAL = models.TextField()	
#     TX_DETALLE_MANUAL = models.TextField()
#     CONTROL	= models.TextField()
#     FECHA	= models.TextField()
#     POC	= models.TextField()
#     OBSERVACIONES= models.TextField()
#     TRACKER	= models.TextField()
#     ATT_ID	= models.TextField()
#     NOMBRE	= models.TextField()
#     LATITUD	= models.TextField()
#     LONGITUD	= models.TextField()
#     ESTADO	= models.TextField()
#     MUNICIPIO	= models.TextField()
#     MERCADO	= models.TextField()
#     REGION_CELULAR	= models.TextField()
#     REGION	= models.TextField()
#     VENDOR	= models.TextField()
#     COBERTURA	= models.TextField()
#     TIPO	= models.TextField()
#     PROYECTO	= models.TextField()
#     CLASIFICACION	= models.TextField()
#     CONTROL_CAMBIOS_RAN	= models.TextField()
#     BASE_ORIGEN_TX	= models.TextField()
#     GRUPOS_MEDIO_TX = models.TextField()
#     TX_DETALLE	= models.TextField()
#     BASE_ORIGEN_TX	= models.TextField()
#     GRUPOS_MEDIO_TX	= models.TextField()
#     TX_DETALLE	= models.TextField()
#     CAPACIDAD	= models.TextField()
#     CONTROL	= models.TextField()
#     CONTROL_CAMBIOS_RAN	= models.TextField()
#     BASE_ORIGEN_TX	= models.TextField()
#     GRUPOS_MEDIO_TX	= models.TextField()
#     TX_DETALLE	= models.TextField()
#     PANDA	= models.TextField()
#     STATUS	= models.TextField()
#     TX_TYPE	= models.TextField()
#     REAL_MIGRACION	= models.TextField()
#     NUMERO= models.IntegerField()
#     class Meta:
#             db_table = 'base_sin_tx'  

# class BaseFiltroSinTX(models.Model):                    
#     ID_ATT= models.TextField()	
#     TX	= models.TextField()
#     TX_GRUPOS_MANUAL = models.TextField()	
#     TX_DETALLE_MANUAL = models.TextField()
#     CONTROL	= models.TextField()
#     FECHA	= models.TextField()
#     POC	= models.TextField()
#     OBSERVACIONES= models.TextField()
    
#     class Meta:
#             db_table = 'tb1_base_sin_tx'  